version: 2

jobs:
  build:
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
  test:
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
  hithere:
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - run: echo "hellooooo"
workflows:
  version: 2
  build_test_and_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
